services:
  react-app:
    build:
      context: .
      secrets:
        - tmdb_token
    ports:
      - "3000:3000"
    container_name: my-movie-app
    restart: unless-stopped

secrets:
  tmdb_token:
    file: ./.tmdb_token